# Generated by Django 5.2.13 on 2026-04-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEventReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(db_index=True, max_length=64)),
                ('dedup_key', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('external_id', models.CharField(db_index=True, max_length=128)),
                ('content_hash', models.CharField(max_length=64)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['integration', 'event_type', 'created_at'], name='integration_integra_830c09_idx')],
            },
        ),
    ]
