# Generated by Django 5.2.13 on 2026-04-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0004_remove_departamentosap_legacy"),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoSap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(db_index=True, max_length=64)),
                ('code', models.IntegerField(help_text='Código do departamento no SAP (Code / DepartmentID).')),
                ('name', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Objeto bruto retornado pela API.')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Departamento SAP',
                'verbose_name_plural': 'Departamentos SAP',
                'db_table': 'departamentossap',
                'ordering': ('company_id', 'code'),
                'constraints': [models.UniqueConstraint(fields=('company_id', 'code'), name='uniq_departamentossap_company_code')],
            },
        ),
    ]
