# Generated by Django 5.2.13 on 2026-04-23 16:15

import django.utils.timezone
from django.db import migrations, models


def _table_exists(cursor, name: str) -> bool:
    cursor.execute(
        """
        SELECT 1 FROM pg_tables
        WHERE schemaname = current_schema() AND tablename = %s
        """,
        [name],
    )
    return cursor.fetchone() is not None


def _column_exists(cursor, table: str, column: str) -> bool:
    cursor.execute(
        """
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = %s AND column_name = %s
        """,
        [table, column],
    )
    return cursor.fetchone() is not None


def _column_data_type(cursor, table: str, column: str) -> str | None:
    cursor.execute(
        """
        SELECT data_type FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = %s AND column_name = %s
        """,
        [table, column],
    )
    row = cursor.fetchone()
    return row[0] if row else None


def _drop_unique_constraints(cursor, table: str) -> None:
    cursor.execute(
        """
        SELECT c.conname
        FROM pg_constraint c
        JOIN pg_class t ON c.conrelid = t.oid
        JOIN pg_namespace n ON t.relnamespace = n.oid
        WHERE n.nspname = current_schema() AND t.relname = %s AND c.contype = 'u'
        """,
        [table],
    )
    for (cn,) in cursor.fetchall():
        cursor.execute('ALTER TABLE "%s" DROP CONSTRAINT IF EXISTS "%s"' % (table, cn))


def _drop_non_primary_indexes(cursor, table: str) -> None:
    """Remove índices secundários (ex.: ``varchar_pattern_ops`` em ``code``) antes de mudar o tipo."""
    cursor.execute("SELECT current_schema()")
    schema = cursor.fetchone()[0]
    cursor.execute(
        """
        SELECT ci.relname
        FROM pg_index i
        JOIN pg_class ti ON ti.oid = i.indrelid
        JOIN pg_class ci ON ci.oid = i.indexrelid
        JOIN pg_namespace ni ON ni.oid = ti.relnamespace
        WHERE ni.nspname = current_schema() AND ti.relname = %s
          AND NOT i.indisprimary
        """,
        [table],
    )
    for (iname,) in cursor.fetchall():
        cursor.execute(
            'DROP INDEX IF EXISTS "%s"."%s" CASCADE' % (schema, iname.replace('"', ""))
        )


def _drop_constraint_if_exists(cursor, table: str, constraint: str) -> None:
    cursor.execute(
        """
        SELECT 1 FROM pg_constraint c
        JOIN pg_class t ON c.conrelid = t.oid
        JOIN pg_namespace n ON t.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND t.relname = %s
          AND c.conname = %s
        """,
        [table, constraint],
    )
    if cursor.fetchone():
        cursor.execute('ALTER TABLE "%s" DROP CONSTRAINT "%s"' % (table, constraint))


def _constraint_on_table_exists(cursor, table: str, constraint: str) -> bool:
    cursor.execute(
        """
        SELECT 1 FROM pg_constraint c
        JOIN pg_class t ON c.conrelid = t.oid
        JOIN pg_namespace n ON t.relnamespace = n.oid
        WHERE n.nspname = current_schema()
          AND t.relname = %s
          AND c.conname = %s
        """,
        [table, constraint],
    )
    return cursor.fetchone() is not None


def _ensure_django_columns_departamentos_sap(cursor) -> None:
    """Compatibiliza tabela legada (``criado_em`` / ``atualizado_em``) com o modelo."""
    if not _table_exists(cursor, "departamentos_sap"):
        return
    if not _column_exists(cursor, "departamentos_sap", "company_id"):
        cursor.execute(
            'ALTER TABLE "departamentos_sap" ADD COLUMN company_id varchar(64) NOT NULL DEFAULT \'\''
        )
        cursor.execute('ALTER TABLE "departamentos_sap" ALTER COLUMN company_id DROP DEFAULT')
    if not _column_exists(cursor, "departamentos_sap", "payload"):
        cursor.execute(
            'ALTER TABLE "departamentos_sap" ADD COLUMN payload jsonb NOT NULL DEFAULT \'{}\'::jsonb'
        )
        cursor.execute('ALTER TABLE "departamentos_sap" ALTER COLUMN payload DROP DEFAULT')
    dt = _column_data_type(cursor, "departamentos_sap", "code")
    if dt == "character varying":
        _drop_unique_constraints(cursor, "departamentos_sap")
        _drop_non_primary_indexes(cursor, "departamentos_sap")
        cursor.execute(
            'ALTER TABLE "departamentos_sap" ALTER COLUMN code TYPE integer '
            "USING trim(both from code::text)::integer"
        )


def _ensure_unique_company_code(cursor, table: str = "departamentos_sap") -> None:
    _drop_constraint_if_exists(cursor, table, "uniq_departamentossap_company_code")
    if not _constraint_on_table_exists(cursor, table, "uniq_departamentos_sap_company_code"):
        cursor.execute(
            'ALTER TABLE "%s" ADD CONSTRAINT "uniq_departamentos_sap_company_code" '
            "UNIQUE (company_id, code)" % table
        )


def _ensure_unique_before_merge(cursor) -> None:
    _drop_constraint_if_exists(cursor, "departamentos_sap", "uniq_departamentossap_company_code")
    if not _constraint_on_table_exists(cursor, "departamentos_sap", "uniq_departamentos_sap_company_code"):
        cursor.execute(
            'ALTER TABLE "departamentos_sap" ADD CONSTRAINT "uniq_departamentos_sap_company_code" '
            "UNIQUE (company_id, code)"
        )


def adapt_departamentos_sap_table(apps, schema_editor):
    """Tabela final ``departamentos_sap`` no ``historico_clientes`` (legado ou Django)."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    with connection.cursor() as cursor:
        old = _table_exists(cursor, "departamentossap")
        new = _table_exists(cursor, "departamentos_sap")

        if old and not new:
            cursor.execute('ALTER TABLE "departamentossap" RENAME TO "departamentos_sap"')
            new = True
            old = False

        new = _table_exists(cursor, "departamentos_sap")
        old = _table_exists(cursor, "departamentossap")

        if new:
            _ensure_django_columns_departamentos_sap(cursor)

        if old and new:
            _ensure_unique_before_merge(cursor)
            cursor.execute(
                """
                INSERT INTO "departamentos_sap" (
                    company_id, code, name, description, payload, atualizado_em, criado_em
                )
                SELECT
                    company_id,
                    code,
                    LEFT(COALESCE(NULLIF(trim(COALESCE(name, '')), ''), ''), 512),
                    COALESCE(NULLIF(trim(COALESCE(description, '')), ''), ''),
                    COALESCE(payload, '{}'::jsonb),
                    COALESCE(synced_at, NOW()),
                    COALESCE(synced_at, NOW())
                FROM "departamentossap"
                ON CONFLICT (company_id, code) DO UPDATE SET
                    name = EXCLUDED.name,
                    description = EXCLUDED.description,
                    payload = EXCLUDED.payload,
                    atualizado_em = EXCLUDED.atualizado_em
                """
            )
            cursor.execute('DROP TABLE IF EXISTS "departamentossap" CASCADE')

        new = _table_exists(cursor, "departamentos_sap")
        if new:
            _ensure_unique_company_code(cursor)


class Migration(migrations.Migration):

    dependencies = [
        ("historico_sap", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(adapt_departamentos_sap_table, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="departamentosap",
                    table="departamentos_sap",
                ),
                migrations.RemoveConstraint(
                    model_name="departamentosap",
                    name="uniq_departamentossap_company_code",
                ),
                migrations.AddConstraint(
                    model_name="departamentosap",
                    constraint=models.UniqueConstraint(
                        fields=("company_id", "code"),
                        name="uniq_departamentos_sap_company_code",
                    ),
                ),
                migrations.AddField(
                    model_name="departamentosap",
                    name="criado_em",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        default=django.utils.timezone.now,
                    ),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name="departamentosap",
                    name="synced_at",
                    field=models.DateTimeField(
                        blank=True,
                        db_column="atualizado_em",
                        help_text="Última sincronização com o Service Layer (coluna legada ``atualizado_em``).",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
