# Generated by Django 5.2.13 on 2026-04-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_sap', '0002_rename_departamentos_sap_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentosap',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_column='criado_em'),
        ),
    ]
