# Generated by Django 5.2.13 on 2026-04-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_sap', '0003_alter_departamentosap_criado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(db_index=True, max_length=64)),
                ('dedupe_key', models.CharField(db_index=True, help_text='Chave derivada da API, ex.: i:1 ou u:MANAGER.', max_length=256)),
                ('internal_key', models.IntegerField(blank=True, null=True)),
                ('user_code', models.CharField(blank=True, max_length=254)),
                ('raw_json', models.JSONField(default=dict, help_text='Objeto bruto retornado pelo Service Layer (GET Users).')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuário SAP (raw)',
                'verbose_name_plural': 'Usuários SAP (raw)',
                'db_table': 'usuarios_sap',
                'ordering': ('company_id', 'dedupe_key'),
                'constraints': [models.UniqueConstraint(fields=('company_id', 'dedupe_key'), name='uniq_usuarios_sap_company_dedupe')],
            },
        ),
    ]
