# Generated by Django 5.2.13 on 2026-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_sap', '0004_usuarios_sap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosap',
            name='raw_json',
            field=models.JSONField(default=dict, help_text='Somente o objeto do usuário (campos SAP), sem OData nem envelope ``User``.'),
        ),
    ]
