# Generated by Django 5.2.13 on 2026-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_sap', '0005_usuario_sap_raw_json_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosap',
            name='raw_json',
            field=models.JSONField(default=dict, help_text='JSON reduzido: InternalKey, UserCode, UserName, eMail, MobilePhoneNumber, Department.'),
        ),
    ]
