# Generated by Django 5.2.13 on 2026-04-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftdeskChamadoState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('remote_updated_at', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Softdesk chamado fingerprint',
                'verbose_name_plural': 'Softdesk chamado fingerprints',
            },
        ),
        migrations.CreateModel(
            name='SoftdeskSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='chamados', max_length=64, unique=True)),
                ('watermark', models.CharField(blank=True, default='', max_length=128)),
                ('page_cursor', models.CharField(blank=True, default='', max_length=512)),
                ('last_poll_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('scope',),
            },
        ),
    ]
