# Generated by Django 6.0.4 on 2026-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('base_url', models.URLField(max_length=512)),
                ('company_db', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password_encrypted', models.TextField(help_text='Fernet-encrypted SAP password')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SAP configuration',
                'verbose_name_plural': 'SAP configurations',
            },
        ),
    ]
