# Generated by Django 6.0.4 on 2026-04-17 12:03

from django.db import migrations, models


def copy_sapconfig_to_credentials(apps, schema_editor):
    SapConfig = apps.get_model("integrations", "SapConfig")
    SapClientCredential = apps.get_model("integrations", "SapClientCredential")
    for row in SapConfig.objects.all():
        SapClientCredential.objects.create(
            client_code=row.company_id,
            client_name="",
            company_id=row.company_id,
            base_url=row.base_url,
            company_db=row.company_db,
            username=row.username,
            password_encrypted=row.password_encrypted,
            active=row.active,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapClientCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(db_index=True, help_text='Código interno do cliente (ex.: código no ERP principal).', max_length=64, unique=True)),
                ('client_name', models.CharField(blank=True, help_text='Nome legível do cliente (opcional).', max_length=256)),
                ('company_id', models.CharField(db_index=True, help_text='Identificador enviado no JWT (claim company_id) para localizar estas credenciais.', max_length=64, unique=True)),
                ('base_url', models.URLField(max_length=512)),
                ('company_db', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password_encrypted', models.TextField(help_text='Senha do Service Layer criptografada (Fernet).')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial SAP por cliente',
                'verbose_name_plural': 'Credenciais SAP por cliente',
                'db_table': 'sap_client_credentials',
                'ordering': ('client_code',),
            },
        ),
        migrations.RunPython(copy_sapconfig_to_credentials, noop_reverse),
        migrations.DeleteModel(
            name='SapConfig',
        ),
    ]
